apiVersion: v1
kind: Secret
metadata:
  name: wg-{{ .Values.name }}-keys
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  WG_PRIVATE_KEY: {{ .Values.config.private_key | quote }}
  WG_PEER_PUBLIC_KEY: {{ .Values.peer.public_key | quote }}
  {{- with .Values.peer.preshared_key }}
  WG_PEER_PRESHARED_KEY: {{ . | quote }}
  {{- end }}
