name: Publish wireguard image and chart
on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  publish:
    uses: garuda-tunnel/.github/.github/workflows/publish-component.yml@main
    with:
      image_name: ghcr.io/garuda-tunnel/garuda-wireguard
      image_context: kube/image
      chart_path: kube/charts/wireguard
    secrets: inherit
